export interface Country {
  name: string;
  slug: string;
  flag: string;
  region: string;
}

export const COUNTRIES: Country[] = [
  // ─── South Asia ───
  { name: "India", slug: "india", flag: "🇮🇳", region: "South Asia" },
  { name: "Pakistan", slug: "pakistan", flag: "🇵🇰", region: "South Asia" },
  { name: "Bangladesh", slug: "bangladesh", flag: "🇧🇩", region: "South Asia" },
  { name: "Sri Lanka", slug: "sri-lanka", flag: "🇱🇰", region: "South Asia" },
  { name: "Nepal", slug: "nepal", flag: "🇳🇵", region: "South Asia" },
  { name: "Bhutan", slug: "bhutan", flag: "🇧🇹", region: "South Asia" },
  { name: "Maldives", slug: "maldives", flag: "🇲🇻", region: "South Asia" },

  // ─── East & Southeast Asia ───
  { name: "China", slug: "china", flag: "🇨🇳", region: "East & Southeast Asia" },
  { name: "Japan", slug: "japan", flag: "🇯🇵", region: "East & Southeast Asia" },
  { name: "South Korea", slug: "south-korea", flag: "🇰🇷", region: "East & Southeast Asia" },
  { name: "North Korea", slug: "north-korea", flag: "🇰🇵", region: "East & Southeast Asia" },
  { name: "Taiwan", slug: "taiwan", flag: "🇹🇼", region: "East & Southeast Asia" },
  { name: "Mongolia", slug: "mongolia", flag: "🇲🇳", region: "East & Southeast Asia" },
  { name: "Singapore", slug: "singapore", flag: "🇸🇬", region: "East & Southeast Asia" },
  { name: "Indonesia", slug: "indonesia", flag: "🇮🇩", region: "East & Southeast Asia" },
  { name: "Philippines", slug: "philippines", flag: "🇵🇭", region: "East & Southeast Asia" },
  { name: "Vietnam", slug: "vietnam", flag: "🇻🇳", region: "East & Southeast Asia" },
  { name: "Thailand", slug: "thailand", flag: "🇹🇭", region: "East & Southeast Asia" },
  { name: "Malaysia", slug: "malaysia", flag: "🇲🇾", region: "East & Southeast Asia" },
  { name: "Myanmar", slug: "myanmar", flag: "🇲🇲", region: "East & Southeast Asia" },
  { name: "Cambodia", slug: "cambodia", flag: "🇰🇭", region: "East & Southeast Asia" },
  { name: "Laos", slug: "laos", flag: "🇱🇦", region: "East & Southeast Asia" },
  { name: "Brunei", slug: "brunei", flag: "🇧🇳", region: "East & Southeast Asia" },
  { name: "Timor-Leste", slug: "timor-leste", flag: "🇹🇱", region: "East & Southeast Asia" },

  // ─── Central Asia ───
  { name: "Kazakhstan", slug: "kazakhstan", flag: "🇰🇿", region: "Central Asia" },
  { name: "Uzbekistan", slug: "uzbekistan", flag: "🇺🇿", region: "Central Asia" },
  { name: "Turkmenistan", slug: "turkmenistan", flag: "🇹🇲", region: "Central Asia" },
  { name: "Tajikistan", slug: "tajikistan", flag: "🇹🇯", region: "Central Asia" },
  { name: "Kyrgyzstan", slug: "kyrgyzstan", flag: "🇰🇬", region: "Central Asia" },

  // ─── Middle East ───
  { name: "Saudi Arabia", slug: "saudi-arabia", flag: "🇸🇦", region: "Middle East" },
  { name: "UAE", slug: "uae", flag: "🇦🇪", region: "Middle East" },
  { name: "Iran", slug: "iran", flag: "🇮🇷", region: "Middle East" },
  { name: "Iraq", slug: "iraq", flag: "🇮🇶", region: "Middle East" },
  { name: "Israel", slug: "israel", flag: "🇮🇱", region: "Middle East" },
  { name: "Palestine", slug: "palestine", flag: "🇵🇸", region: "Middle East" },
  { name: "Turkey", slug: "turkey", flag: "🇹🇷", region: "Middle East" },
  { name: "Afghanistan", slug: "afghanistan", flag: "🇦🇫", region: "Middle East" },
  { name: "Lebanon", slug: "lebanon", flag: "🇱🇧", region: "Middle East" },
  { name: "Syria", slug: "syria", flag: "🇸🇾", region: "Middle East" },
  { name: "Yemen", slug: "yemen", flag: "🇾🇪", region: "Middle East" },
  { name: "Jordan", slug: "jordan", flag: "🇯🇴", region: "Middle East" },
  { name: "Kuwait", slug: "kuwait", flag: "🇰🇼", region: "Middle East" },
  { name: "Qatar", slug: "qatar", flag: "🇶🇦", region: "Middle East" },
  { name: "Bahrain", slug: "bahrain", flag: "🇧🇭", region: "Middle East" },
  { name: "Oman", slug: "oman", flag: "🇴🇲", region: "Middle East" },
  { name: "Cyprus", slug: "cyprus", flag: "🇨🇾", region: "Middle East" },
  { name: "Armenia", slug: "armenia", flag: "🇦🇲", region: "Middle East" },
  { name: "Azerbaijan", slug: "azerbaijan", flag: "🇦🇿", region: "Middle East" },
  { name: "Georgia", slug: "georgia", flag: "🇬🇪", region: "Middle East" },

  // ─── Africa ───
  { name: "Nigeria", slug: "nigeria", flag: "🇳🇬", region: "Africa" },
  { name: "Ethiopia", slug: "ethiopia", flag: "🇪🇹", region: "Africa" },
  { name: "Egypt", slug: "egypt", flag: "🇪🇬", region: "Africa" },
  { name: "South Africa", slug: "south-africa", flag: "🇿🇦", region: "Africa" },
  { name: "Kenya", slug: "kenya", flag: "🇰🇪", region: "Africa" },
  { name: "Ghana", slug: "ghana", flag: "🇬🇭", region: "Africa" },
  { name: "DRC Congo", slug: "drc-congo", flag: "🇨🇩", region: "Africa" },
  { name: "Morocco", slug: "morocco", flag: "🇲🇦", region: "Africa" },
  { name: "Zimbabwe", slug: "zimbabwe", flag: "🇿🇼", region: "Africa" },
  { name: "Tanzania", slug: "tanzania", flag: "🇹🇿", region: "Africa" },
  { name: "Uganda", slug: "uganda", flag: "🇺🇬", region: "Africa" },
  { name: "Algeria", slug: "algeria", flag: "🇩🇿", region: "Africa" },
  { name: "Sudan", slug: "sudan", flag: "🇸🇩", region: "Africa" },
  { name: "South Sudan", slug: "south-sudan", flag: "🇸🇸", region: "Africa" },
  { name: "Tunisia", slug: "tunisia", flag: "🇹🇳", region: "Africa" },
  { name: "Libya", slug: "libya", flag: "🇱🇾", region: "Africa" },
  { name: "Senegal", slug: "senegal", flag: "🇸🇳", region: "Africa" },
  { name: "Ivory Coast", slug: "ivory-coast", flag: "🇨🇮", region: "Africa" },
  { name: "Cameroon", slug: "cameroon", flag: "🇨🇲", region: "Africa" },
  { name: "Angola", slug: "angola", flag: "🇦🇴", region: "Africa" },
  { name: "Mozambique", slug: "mozambique", flag: "🇲🇿", region: "Africa" },
  { name: "Madagascar", slug: "madagascar", flag: "🇲🇬", region: "Africa" },
  { name: "Mali", slug: "mali", flag: "🇲🇱", region: "Africa" },
  { name: "Zambia", slug: "zambia", flag: "🇿🇲", region: "Africa" },
  { name: "Malawi", slug: "malawi", flag: "🇲🇼", region: "Africa" },
  { name: "Somalia", slug: "somalia", flag: "🇸🇴", region: "Africa" },
  { name: "Rwanda", slug: "rwanda", flag: "🇷🇼", region: "Africa" },
  { name: "Burundi", slug: "burundi", flag: "🇧🇮", region: "Africa" },
  { name: "Benin", slug: "benin", flag: "🇧🇯", region: "Africa" },
  { name: "Burkina Faso", slug: "burkina-faso", flag: "🇧🇫", region: "Africa" },
  { name: "Niger", slug: "niger", flag: "🇳🇪", region: "Africa" },
  { name: "Chad", slug: "chad", flag: "🇹🇩", region: "Africa" },
  { name: "Guinea", slug: "guinea", flag: "🇬🇳", region: "Africa" },
  { name: "Sierra Leone", slug: "sierra-leone", flag: "🇸🇱", region: "Africa" },
  { name: "Liberia", slug: "liberia", flag: "🇱🇷", region: "Africa" },
  { name: "Central African Republic", slug: "central-african-republic", flag: "🇨🇫", region: "Africa" },
  { name: "Republic of the Congo", slug: "republic-of-the-congo", flag: "🇨🇬", region: "Africa" },
  { name: "Gabon", slug: "gabon", flag: "🇬🇦", region: "Africa" },
  { name: "Equatorial Guinea", slug: "equatorial-guinea", flag: "🇬🇶", region: "Africa" },
  { name: "Togo", slug: "togo", flag: "🇹🇬", region: "Africa" },
  { name: "Eritrea", slug: "eritrea", flag: "🇪🇷", region: "Africa" },
  { name: "Djibouti", slug: "djibouti", flag: "🇩🇯", region: "Africa" },
  { name: "Mauritania", slug: "mauritania", flag: "🇲🇷", region: "Africa" },
  { name: "Namibia", slug: "namibia", flag: "🇳🇦", region: "Africa" },
  { name: "Botswana", slug: "botswana", flag: "🇧🇼", region: "Africa" },
  { name: "Lesotho", slug: "lesotho", flag: "🇱🇸", region: "Africa" },
  { name: "Eswatini", slug: "eswatini", flag: "🇸🇿", region: "Africa" },
  { name: "Gambia", slug: "gambia", flag: "🇬🇲", region: "Africa" },
  { name: "Guinea-Bissau", slug: "guinea-bissau", flag: "🇬🇼", region: "Africa" },
  { name: "Mauritius", slug: "mauritius", flag: "🇲🇺", region: "Africa" },
  { name: "Comoros", slug: "comoros", flag: "🇰🇲", region: "Africa" },
  { name: "Cape Verde", slug: "cape-verde", flag: "🇨🇻", region: "Africa" },
  { name: "São Tomé and Príncipe", slug: "sao-tome-and-principe", flag: "🇸🇹", region: "Africa" },
  { name: "Seychelles", slug: "seychelles", flag: "🇸🇨", region: "Africa" },

  // ─── Eastern Europe ───
  { name: "Russia", slug: "russia", flag: "🇷🇺", region: "Eastern Europe" },
  { name: "Ukraine", slug: "ukraine", flag: "🇺🇦", region: "Eastern Europe" },
  { name: "Poland", slug: "poland", flag: "🇵🇱", region: "Eastern Europe" },
  { name: "Romania", slug: "romania", flag: "🇷🇴", region: "Eastern Europe" },
  { name: "Czech Republic", slug: "czech-republic", flag: "🇨🇿", region: "Eastern Europe" },
  { name: "Hungary", slug: "hungary", flag: "🇭🇺", region: "Eastern Europe" },
  { name: "Belarus", slug: "belarus", flag: "🇧🇾", region: "Eastern Europe" },
  { name: "Bulgaria", slug: "bulgaria", flag: "🇧🇬", region: "Eastern Europe" },
  { name: "Serbia", slug: "serbia", flag: "🇷🇸", region: "Eastern Europe" },
  { name: "Croatia", slug: "croatia", flag: "🇭🇷", region: "Eastern Europe" },
  { name: "Slovakia", slug: "slovakia", flag: "🇸🇰", region: "Eastern Europe" },
  { name: "Slovenia", slug: "slovenia", flag: "🇸🇮", region: "Eastern Europe" },
  { name: "Bosnia and Herzegovina", slug: "bosnia-and-herzegovina", flag: "🇧🇦", region: "Eastern Europe" },
  { name: "North Macedonia", slug: "north-macedonia", flag: "🇲🇰", region: "Eastern Europe" },
  { name: "Albania", slug: "albania", flag: "🇦🇱", region: "Eastern Europe" },
  { name: "Kosovo", slug: "kosovo", flag: "🇽🇰", region: "Eastern Europe" },
  { name: "Montenegro", slug: "montenegro", flag: "🇲🇪", region: "Eastern Europe" },
  { name: "Moldova", slug: "moldova", flag: "🇲🇩", region: "Eastern Europe" },
  { name: "Lithuania", slug: "lithuania", flag: "🇱🇹", region: "Eastern Europe" },
  { name: "Latvia", slug: "latvia", flag: "🇱🇻", region: "Eastern Europe" },
  { name: "Estonia", slug: "estonia", flag: "🇪🇪", region: "Eastern Europe" },
  { name: "Greece", slug: "greece", flag: "🇬🇷", region: "Eastern Europe" },

  // ─── Western World ───
  { name: "USA", slug: "usa", flag: "🇺🇸", region: "Western World" },
  { name: "Canada", slug: "canada", flag: "🇨🇦", region: "Western World" },
  { name: "UK", slug: "uk", flag: "🇬🇧", region: "Western World" },
  { name: "Germany", slug: "germany", flag: "🇩🇪", region: "Western World" },
  { name: "France", slug: "france", flag: "🇫🇷", region: "Western World" },
  { name: "Italy", slug: "italy", flag: "🇮🇹", region: "Western World" },
  { name: "Spain", slug: "spain", flag: "🇪🇸", region: "Western World" },
  { name: "Portugal", slug: "portugal", flag: "🇵🇹", region: "Western World" },
  { name: "Switzerland", slug: "switzerland", flag: "🇨🇭", region: "Western World" },
  { name: "Netherlands", slug: "netherlands", flag: "🇳🇱", region: "Western World" },
  { name: "Belgium", slug: "belgium", flag: "🇧🇪", region: "Western World" },
  { name: "Austria", slug: "austria", flag: "🇦🇹", region: "Western World" },
  { name: "Sweden", slug: "sweden", flag: "🇸🇪", region: "Western World" },
  { name: "Norway", slug: "norway", flag: "🇳🇴", region: "Western World" },
  { name: "Denmark", slug: "denmark", flag: "🇩🇰", region: "Western World" },
  { name: "Finland", slug: "finland", flag: "🇫🇮", region: "Western World" },
  { name: "Iceland", slug: "iceland", flag: "🇮🇸", region: "Western World" },
  { name: "Ireland", slug: "ireland", flag: "🇮🇪", region: "Western World" },
  { name: "Luxembourg", slug: "luxembourg", flag: "🇱🇺", region: "Western World" },
  { name: "Malta", slug: "malta", flag: "🇲🇹", region: "Western World" },
  { name: "Australia", slug: "australia", flag: "🇦🇺", region: "Western World" },
  { name: "New Zealand", slug: "new-zealand", flag: "🇳🇿", region: "Western World" },
  { name: "Monaco", slug: "monaco", flag: "🇲🇨", region: "Western World" },
  { name: "Liechtenstein", slug: "liechtenstein", flag: "🇱🇮", region: "Western World" },
  { name: "Andorra", slug: "andorra", flag: "🇦🇩", region: "Western World" },
  { name: "San Marino", slug: "san-marino", flag: "🇸🇲", region: "Western World" },
  { name: "Vatican City", slug: "vatican-city", flag: "🇻🇦", region: "Western World" },

  // ─── Latin Americas ───
  { name: "Brazil", slug: "brazil", flag: "🇧🇷", region: "Latin Americas" },
  { name: "Argentina", slug: "argentina", flag: "🇦🇷", region: "Latin Americas" },
  { name: "Mexico", slug: "mexico", flag: "🇲🇽", region: "Latin Americas" },
  { name: "Colombia", slug: "colombia", flag: "🇨🇴", region: "Latin Americas" },
  { name: "Chile", slug: "chile", flag: "🇨🇱", region: "Latin Americas" },
  { name: "Peru", slug: "peru", flag: "🇵🇪", region: "Latin Americas" },
  { name: "Venezuela", slug: "venezuela", flag: "🇻🇪", region: "Latin Americas" },
  { name: "Ecuador", slug: "ecuador", flag: "🇪🇨", region: "Latin Americas" },
  { name: "Bolivia", slug: "bolivia", flag: "🇧🇴", region: "Latin Americas" },
  { name: "Paraguay", slug: "paraguay", flag: "🇵🇾", region: "Latin Americas" },
  { name: "Uruguay", slug: "uruguay", flag: "🇺🇾", region: "Latin Americas" },
  { name: "Guatemala", slug: "guatemala", flag: "🇬🇹", region: "Latin Americas" },
  { name: "Honduras", slug: "honduras", flag: "🇭🇳", region: "Latin Americas" },
  { name: "El Salvador", slug: "el-salvador", flag: "🇸🇻", region: "Latin Americas" },
  { name: "Nicaragua", slug: "nicaragua", flag: "🇳🇮", region: "Latin Americas" },
  { name: "Costa Rica", slug: "costa-rica", flag: "🇨🇷", region: "Latin Americas" },
  { name: "Panama", slug: "panama", flag: "🇵🇦", region: "Latin Americas" },
  { name: "Guyana", slug: "guyana", flag: "🇬🇾", region: "Latin Americas" },
  { name: "Suriname", slug: "suriname", flag: "🇸🇷", region: "Latin Americas" },
  { name: "Belize", slug: "belize", flag: "🇧🇿", region: "Latin Americas" },

  // ─── Caribbean ───
  { name: "Cuba", slug: "cuba", flag: "🇨🇺", region: "Caribbean" },
  { name: "Haiti", slug: "haiti", flag: "🇭🇹", region: "Caribbean" },
  { name: "Dominican Republic", slug: "dominican-republic", flag: "🇩🇴", region: "Caribbean" },
  { name: "Jamaica", slug: "jamaica", flag: "🇯🇲", region: "Caribbean" },
  { name: "Trinidad and Tobago", slug: "trinidad-and-tobago", flag: "🇹🇹", region: "Caribbean" },
  { name: "Bahamas", slug: "bahamas", flag: "🇧🇸", region: "Caribbean" },
  { name: "Barbados", slug: "barbados", flag: "🇧🇧", region: "Caribbean" },
  { name: "Saint Lucia", slug: "saint-lucia", flag: "🇱🇨", region: "Caribbean" },
  { name: "Grenada", slug: "grenada", flag: "🇬🇩", region: "Caribbean" },
  { name: "Saint Vincent and the Grenadines", slug: "saint-vincent-and-the-grenadines", flag: "🇻🇨", region: "Caribbean" },
  { name: "Antigua and Barbuda", slug: "antigua-and-barbuda", flag: "🇦🇬", region: "Caribbean" },
  { name: "Dominica", slug: "dominica", flag: "🇩🇲", region: "Caribbean" },
  { name: "Saint Kitts and Nevis", slug: "saint-kitts-and-nevis", flag: "🇰🇳", region: "Caribbean" },

  // ─── Pacific Islands ───
  { name: "Papua New Guinea", slug: "papua-new-guinea", flag: "🇵🇬", region: "Pacific Islands" },
  { name: "Fiji", slug: "fiji", flag: "🇫🇯", region: "Pacific Islands" },
  { name: "Solomon Islands", slug: "solomon-islands", flag: "🇸🇧", region: "Pacific Islands" },
  { name: "Vanuatu", slug: "vanuatu", flag: "🇻🇺", region: "Pacific Islands" },
  { name: "Samoa", slug: "samoa", flag: "🇼🇸", region: "Pacific Islands" },
  { name: "Tonga", slug: "tonga", flag: "🇹🇴", region: "Pacific Islands" },
  { name: "Kiribati", slug: "kiribati", flag: "🇰🇮", region: "Pacific Islands" },
  { name: "Micronesia", slug: "micronesia", flag: "🇫🇲", region: "Pacific Islands" },
  { name: "Marshall Islands", slug: "marshall-islands", flag: "🇲🇭", region: "Pacific Islands" },
  { name: "Palau", slug: "palau", flag: "🇵🇼", region: "Pacific Islands" },
  { name: "Tuvalu", slug: "tuvalu", flag: "🇹🇻", region: "Pacific Islands" },
  { name: "Nauru", slug: "nauru", flag: "🇳🇷", region: "Pacific Islands" },
];

export function getCountryBySlug(slug: string): Country | undefined {
  return COUNTRIES.find((c) => c.slug === slug);
}

export function getCountriesByRegion(): Record<string, Country[]> {
  const grouped: Record<string, Country[]> = {};
  for (const country of COUNTRIES) {
    if (!grouped[country.region]) grouped[country.region] = [];
    grouped[country.region].push(country);
  }
  return grouped;
}
