"use client";

import { PremiumGate } from "@/app/components/premium-gate";
import Link from "next/link";

// Mock deep dive data — will be replaced with real Sonnet calls later
const MOCK_ANALYSIS = {
  headline: "Ukraine-Russia peace talks day 3: land remains core sticking point; Trump demands speed",
  category: "World",
  date: "February 18, 2026",
  regions: ["Eastern Europe", "West"],
  significance: "high" as const,

  whatIsBeingSaid: [
    "Both sides describe the talks as 'constructive' while disagreeing on fundamentals",
    "Western media emphasizes Trump's pressure for rapid resolution",
    "Russian state media frames territorial gains as non-negotiable starting points",
    "Ukrainian sources stress sovereignty as the red line",
    "European leaders push for a framework that avoids setting precedent for territorial seizure",
  ],

  whatIsBeingOmitted: [
    "The specific territorial concessions being discussed behind closed doors",
    "The role of private diplomatic channels running parallel to Geneva",
    "Economic pressure from energy markets shaping both sides' timelines",
    "Civilian displacement data from contested regions",
    "The gap between public negotiating positions and private flexibility",
  ],

  emotionalFraming: {
    urgency: 85,
    fear: 60,
    hope: 40,
    anger: 55,
    analysis: "Coverage overwhelmingly uses urgency framing ('time is running out', 'critical window'). This creates pressure to accept any deal rather than evaluating terms. Fear framing is moderate but concentrated in European outlets. Hope framing is notably absent from Eastern European coverage but present in Western editorial pieces.",
  },

  broaderPatterns: [
    {
      pattern: "Temporal Displacement",
      explanation: "The pressure for speed displaces the question of whether a fast deal is a good deal. Historical parallels (hasty post-conflict agreements that collapsed) are absent from mainstream coverage.",
    },
    {
      pattern: "Sovereignty Theatre",
      explanation: "Both sides perform sovereignty claims publicly while the actual negotiations operate on different logic — resource access, security guarantees, and sphere-of-influence recognition.",
    },
    {
      pattern: "Information Asymmetry",
      explanation: "Negotiators have access to intelligence and economic data that fundamentally shapes their positions, but public discourse operates without this context, making informed democratic debate impossible.",
    },
  ],

  sourceSpread: {
    total: 47,
    regions: 5,
    languages: 4,
  },
};

export default function DeepDivePage() {
  return (
    <PremiumGate>
      <DeepDiveContent />
    </PremiumGate>
  );
}

function DeepDiveContent() {
  const d = MOCK_ANALYSIS;

  return (
    <main>
      {/* Header */}
      <section className="border-b border-zinc-200 py-12 dark:border-zinc-800/50 md:py-16">
        <div className="mx-auto max-w-3xl px-6">
          {/* AI badge */}
          <div className="inline-flex items-center gap-2 rounded-full border border-violet-200 bg-violet-50 px-3 py-1 text-xs font-medium text-violet-700 dark:border-violet-800/50 dark:bg-violet-950/30 dark:text-violet-400">
            <svg
              width="12"
              height="12"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
              strokeLinecap="round"
              strokeLinejoin="round"
            >
              <path d="M12 2L2 7l10 5 10-5-10-5z" />
              <path d="M2 17l10 5 10-5" />
              <path d="M2 12l10 5 10-5" />
            </svg>
            Generated by AI analysis
          </div>

          <h1 className="mt-6 text-2xl font-semibold leading-snug tracking-tight text-zinc-800 dark:text-zinc-100 md:text-3xl">
            {d.headline}
          </h1>

          <div className="mt-4 flex flex-wrap items-center gap-3 text-sm">
            <time className="text-zinc-400 dark:text-zinc-500">{d.date}</time>
            <span className="text-zinc-300 dark:text-zinc-700">&middot;</span>
            <span className="text-zinc-400 dark:text-zinc-500">{d.category}</span>
            <span className="text-zinc-300 dark:text-zinc-700">&middot;</span>
            <span className="text-zinc-400 dark:text-zinc-500">
              {d.sourceSpread.total} sources across {d.sourceSpread.regions} regions
            </span>
          </div>

          {/* Region tags */}
          <div className="mt-3 flex flex-wrap gap-1.5">
            {d.regions.map((r) => (
              <span
                key={r}
                className="inline-flex rounded bg-zinc-100 px-1.5 py-0.5 text-[10px] font-medium text-zinc-500 dark:bg-zinc-800 dark:text-zinc-500"
              >
                {r}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* What Is Being Said */}
      <section className="border-b border-zinc-200 py-12 dark:border-zinc-800/50">
        <div className="mx-auto max-w-3xl px-6">
          <div className="flex items-center gap-3">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-blue-50 dark:bg-blue-950/30">
              <svg
                width="16"
                height="16"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.5"
                className="text-blue-600 dark:text-blue-400"
              >
                <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
              </svg>
            </div>
            <h2 className="text-xs font-medium uppercase tracking-[0.2em] text-blue-600 dark:text-blue-400">
              What Is Being Said
            </h2>
          </div>
          <ul className="mt-6 space-y-3">
            {d.whatIsBeingSaid.map((point, i) => (
              <li
                key={i}
                className="flex gap-3 text-sm leading-relaxed text-zinc-600 dark:text-zinc-400"
              >
                <span className="mt-2 block h-1 w-1 flex-shrink-0 rounded-full bg-blue-400 dark:bg-blue-500" />
                <span>{point}</span>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* What Is Being Omitted */}
      <section className="border-b border-zinc-200 py-12 dark:border-zinc-800/50">
        <div className="mx-auto max-w-3xl px-6">
          <div className="flex items-center gap-3">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-red-50 dark:bg-red-950/30">
              <svg
                width="16"
                height="16"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.5"
                className="text-red-600 dark:text-red-400"
              >
                <circle cx="12" cy="12" r="10" />
                <line x1="4.93" y1="4.93" x2="19.07" y2="19.07" />
              </svg>
            </div>
            <h2 className="text-xs font-medium uppercase tracking-[0.2em] text-red-600 dark:text-red-400">
              What Is Being Omitted
            </h2>
          </div>
          <ul className="mt-6 space-y-3">
            {d.whatIsBeingOmitted.map((point, i) => (
              <li
                key={i}
                className="flex gap-3 text-sm leading-relaxed text-zinc-600 dark:text-zinc-400"
              >
                <span className="mt-2 block h-1 w-1 flex-shrink-0 rounded-full bg-red-400 dark:bg-red-500" />
                <span>{point}</span>
              </li>
            ))}
          </ul>
        </div>
      </section>

      {/* Emotional Framing Analysis */}
      <section className="border-b border-zinc-200 py-12 dark:border-zinc-800/50">
        <div className="mx-auto max-w-3xl px-6">
          <div className="flex items-center gap-3">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-fuchsia-50 dark:bg-fuchsia-950/30">
              <svg
                width="16"
                height="16"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.5"
                className="text-fuchsia-600 dark:text-fuchsia-400"
              >
                <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z" />
              </svg>
            </div>
            <h2 className="text-xs font-medium uppercase tracking-[0.2em] text-fuchsia-600 dark:text-fuchsia-400">
              Emotional Framing
            </h2>
          </div>

          {/* Bars */}
          <div className="mt-6 space-y-4">
            {(["urgency", "fear", "hope", "anger"] as const).map((key) => {
              const value = d.emotionalFraming[key] as number;
              const barColors: Record<string, string> = {
                urgency: "bg-amber-500",
                fear: "bg-red-400",
                hope: "bg-emerald-400",
                anger: "bg-rose-500",
              };
              return (
                <div key={key}>
                  <div className="flex items-center justify-between">
                    <span className="text-sm capitalize text-zinc-600 dark:text-zinc-400">
                      {key}
                    </span>
                    <span className="text-xs text-zinc-400 dark:text-zinc-500">
                      {value}%
                    </span>
                  </div>
                  <div className="mt-1.5 h-1.5 w-full rounded-full bg-zinc-100 dark:bg-zinc-800">
                    <div
                      className={`h-1.5 rounded-full ${barColors[key]} transition-all`}
                      style={{ width: `${value}%` }}
                    />
                  </div>
                </div>
              );
            })}
          </div>

          <p className="mt-6 text-sm leading-relaxed text-zinc-500 dark:text-zinc-400">
            {d.emotionalFraming.analysis}
          </p>
        </div>
      </section>

      {/* Broader Patterns */}
      <section className="border-b border-zinc-200 py-12 dark:border-zinc-800/50">
        <div className="mx-auto max-w-3xl px-6">
          <div className="flex items-center gap-3">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-violet-50 dark:bg-violet-950/30">
              <svg
                width="16"
                height="16"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="1.5"
                className="text-violet-600 dark:text-violet-400"
              >
                <circle cx="12" cy="12" r="10" />
                <path d="M2 12h20" />
                <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
              </svg>
            </div>
            <h2 className="text-xs font-medium uppercase tracking-[0.2em] text-violet-600 dark:text-violet-400">
              Connection to Broader Patterns
            </h2>
          </div>

          <div className="mt-6 space-y-6">
            {d.broaderPatterns.map((p, i) => (
              <div
                key={i}
                className="rounded-lg border border-zinc-200 p-5 dark:border-zinc-800/50"
              >
                <span className="inline-flex rounded bg-violet-50 px-2 py-0.5 text-xs font-medium text-violet-600 dark:bg-violet-950/30 dark:text-violet-400">
                  {p.pattern}
                </span>
                <p className="mt-3 text-sm leading-relaxed text-zinc-600 dark:text-zinc-400">
                  {p.explanation}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Disclaimer + Nav */}
      <section className="py-12">
        <div className="mx-auto max-w-3xl px-6 text-center">
          <div className="inline-flex items-center gap-2 rounded-full border border-zinc-200 bg-zinc-50 px-4 py-2 text-xs text-zinc-500 dark:border-zinc-800/50 dark:bg-zinc-900/50 dark:text-zinc-400">
            <svg
              width="12"
              height="12"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="2"
            >
              <circle cx="12" cy="12" r="10" />
              <line x1="12" y1="16" x2="12" y2="12" />
              <line x1="12" y1="8" x2="12.01" y2="8" />
            </svg>
            AI-generated analysis. Sources cross-referenced but interpretation is algorithmic.
          </div>

          <div className="mt-8">
            <Link
              href="/briefing"
              className="text-sm text-zinc-400 transition-colors hover:text-zinc-600 dark:hover:text-zinc-300"
            >
              Back to briefing
            </Link>
          </div>
        </div>
      </section>
    </main>
  );
}
