-- 2026-04-25 — Package 3: Transparency / coverage layer.
--
-- Per-company per-day "what was checked today" record. Companion to the
-- briefing: the briefing answers "what should you read"; coverage answers
-- "what did the system look at on your behalf, and what stayed quiet?"
--
-- Intentionally jsonb-heavy. The structured shape is what matters at v1;
-- richer typing arrives in Package 5 alongside the company scan pipeline
-- separation. Owner-only RLS, mirrors company_briefings.
--
-- Idempotent — safe to re-run.

begin;

CREATE TABLE IF NOT EXISTS public.company_coverage_summaries (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  company_profile_id UUID NOT NULL REFERENCES public.company_profiles(id) ON DELETE CASCADE,
  coverage_date DATE NOT NULL,

  -- Array of { type, value, matched_signal_count, last_movement_at }
  -- type is one of: 'theme', 'entity', 'region', 'sector', 'risk', 'supply_chain'
  tracked_items_checked JSONB NOT NULL DEFAULT '[]'::jsonb,

  -- { total: N, by_language: { en: N, ... }, by_region: { ... } }
  sources_inspected JSONB NOT NULL DEFAULT '{}'::jsonb,

  -- Array of signal identifiers that surfaced only outside the mainstream
  -- English-language allowlist. v1 heuristic; revisited in Package 5.
  early_signals JSONB NOT NULL DEFAULT '[]'::jsonb,

  -- Array of { type, value } — tracked items with zero movement today.
  silent_items JSONB NOT NULL DEFAULT '[]'::jsonb,

  -- Optional one-line summary built deterministically from the structured
  -- fields. NOT generated by an LLM.
  summary_text TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT unique_company_coverage UNIQUE (company_profile_id, coverage_date)
);

CREATE INDEX IF NOT EXISTS idx_ccs_company
  ON public.company_coverage_summaries(company_profile_id);
CREATE INDEX IF NOT EXISTS idx_ccs_date
  ON public.company_coverage_summaries(coverage_date DESC);
CREATE INDEX IF NOT EXISTS idx_ccs_tracked_items_gin
  ON public.company_coverage_summaries USING gin (tracked_items_checked);
CREATE INDEX IF NOT EXISTS idx_ccs_sources_gin
  ON public.company_coverage_summaries USING gin (sources_inspected);

ALTER TABLE public.company_coverage_summaries ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view own coverage summaries"
  ON public.company_coverage_summaries;
CREATE POLICY "Users can view own coverage summaries"
  ON public.company_coverage_summaries FOR SELECT
  USING (
    company_profile_id IN (
      SELECT id FROM public.company_profiles WHERE owner_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Service role can manage coverage summaries"
  ON public.company_coverage_summaries;
CREATE POLICY "Service role can manage coverage summaries"
  ON public.company_coverage_summaries FOR ALL
  USING (auth.jwt()->>'role' = 'service_role');

DROP TRIGGER IF EXISTS company_coverage_summaries_updated_at
  ON public.company_coverage_summaries;
CREATE TRIGGER company_coverage_summaries_updated_at
  BEFORE UPDATE ON public.company_coverage_summaries
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at();

commit;
